import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { joinRoom } from '../multiplayer/rooms';
import { supabaseConfigured } from '../multiplayer/client';

function savedName() { try { return localStorage.getItem('jw-display-name') || ''; } catch { return ''; } }
export default function JoinRoom() {
  const [name, setName] = useState(savedName); const [code, setCode] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate();
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { localStorage.setItem('jw-display-name', name.trim()); } catch { /* callsign still works without saved preferences */ } try { const room = await joinRoom(code, name.trim()); navigate(`/lobby/${room.code}`); } catch (err) { setError(err instanceof Error ? err.message : 'Could not join room.'); } finally { setBusy(false); } }
  return <main className="room-page"><div className="landing-grid"/><Link className="room-back" to="/">← JETPACK WARS</Link><section className="room-card"><div className="eyebrow"><span/> SQUAD RENDEZVOUS</div><h1>JOIN<br/><em>YOUR CREW</em></h1><p>Enter the five-character room code shared by your host.</p><form onSubmit={submit}><label htmlFor="room-code">ROOM CODE</label><input id="room-code" className="code-input" maxLength={5} minLength={5} placeholder="7K4P2" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5))} required autoCapitalize="characters"/><label htmlFor="pilot-name">CALLSIGN</label><input id="pilot-name" maxLength={24} minLength={1} placeholder="e.g. SKYRUNNER" value={name} onChange={e=>setName(e.target.value)} required autoComplete="nickname"/><button className="play-button" disabled={busy || !supabaseConfigured || code.length!==5}>{busy?'CONNECTING…':'JOIN ROOM'} <b>↗</b></button></form>{!supabaseConfigured&&<div className="room-error">Multiplayer is temporarily unavailable. Please try again later.</div>}{error&&<div className="room-error">{error}</div>}<div className="room-footnote">ANONYMOUS PILOT ID · NO EMAIL REQUIRED</div></section></main>
}
